name: flutter_addons
description: "Flutter Addons is a powerful toolkit designed to streamline responsive Flutter development. It includes theme engines, layout utilities, scaling extensions, and animation helpers—everything you need to build polished, adaptive apps faster."
version: 2.1.0
homepage: https://github.com/arrahmanbd/flutter_addons
repository: https://github.com/arrahmanbd/flutter_addons
issue_tracker: https://github.com/arrahmanbd/flutter_addons/issues
documentation: https://github.com/arrahmanbd/flutter_addons/wiki
screenshots:
  - description: 'Flutter Addons Icon'
    path: images/icon.png
  - description: 'Flutter Addons Theme Image'
    path: images/cover.jpg
  - description: 'Flutter Addons global design'
    path: images/global.jpg

topics:
  - theme
  - utils
  - extensions
  - responsive
  - spacing
environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
