name: flutter_addons
description: "A productivity-boosting micro-extension framework for Flutter.Boost your development speed by over 7x with a robust set of micro-extensions that help you build fully responsive, theme-aware Flutter apps effortlessly."
version: 2.4.0
homepage: https://github.com/arrahmanbd/flutter_addons
repository: https://github.com/arrahmanbd/flutter_addons
issue_tracker: https://github.com/arrahmanbd/flutter_addons/issues
documentation: https://github.com/arrahmanbd/flutter_addons/wiki
screenshots:
  - description: 'Flutter Addons Icon'
    path: images/icon.png
  - description: 'Flutter Addons cover Image'
    path: images/cover.jpg
  - description: 'Flutter Addons global design'
    path: images/global.jpg
  - description: 'Flutter Addons components'
    path: images/components.jpg

topics:
  - responsive
  - soului
  - utils
  - extensions
  - master

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
