name: flutter_addons
description: "Supercharge your development workflow with Flutter Addons — the ultimate toolkit for building sleek, responsive Flutter apps effortlessly. Packed with powerful theme engines, seamless scaling tools, and thousands of extensions to accelerate development."
version: 2.2.0
homepage: https://github.com/arrahmanbd/flutter_addons
repository: https://github.com/arrahmanbd/flutter_addons
issue_tracker: https://github.com/arrahmanbd/flutter_addons/issues
documentation: https://github.com/arrahmanbd/flutter_addons/wiki
screenshots:
  - description: 'Flutter Addons Icon'
    path: images/icon.png
  - description: 'Flutter Addons cover Image'
    path: images/cover.jpg
  - description: 'Flutter Addons global design'
    path: images/global.jpg

topics:
  - responsive
  - theme
  - utils
  - extensions
  - master
environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
